version: '3.8'

services:
  docs-atlassian-remote:
    build:
      context: .
      target: docs-atlassian-remote
    image: onlyoffice/docs-atlassian-remote:${PRODUCT_VERSION}
    depends_on:
      - postgres
      - redis
    environment:
      - APP_BASE_URL=${APP_BASE_URL}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - FORGE_JIRA_APP_ID=${FORGE_JIRA_APP_ID}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_USERNAME=${REDIS_USERNAME}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_DATA_REDIS_DATABASE=${REDIS_DB}
    stdin_open: true
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    stdin_open: true
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.12
    stdin_open: true
    ports:
      - "6379:6379"
